var elems = {
    'root_section_secPlayer': [],
    'secPlayer_div_player': [],
    'player_div_hymnTts': [],
    'hymnTts_h1_hymnTt': [],
    'hymnTts_h4_hymnOt': [],
    'player_h3_hymnCr': [],
    'player_p_hymnCc': ['innerHTML__Hinário<br>Adventista<br>do Sétimo Dia'],
    'player_h3_hymnInfRnd': [],
    'player_h3_hymnBv': [],
    'secPlayer_audio_srcAud': ['src__','type__audio/mp4'],
    'secPlayer_p_btnsAud': [],
    'btnsAud_input_btnPlay': ['type__button', 'value__♫ Tocar'],
    'btnsAud_input_btnRnd': ['type__button', 'value__♫ Aleatório'],
    'btnsAud_input_btnRndAll': ['type__button', 'value__♫ Todos Aleatórios'],
    'secPlayer_p_audMod': [],
    'audMod_label_labAudModPb': [],
    'labAudModPb_input_audModPb': ['type__radio', 'name__aud-mod'],
    'labAudModPb_span_namePb': ['innerHTML__Playback '],
    'audMod_label_labAudModVo': [],
    'labAudModVo_input_audModVo': ['type__radio', 'name__aud-mod', 'checked__true'],
    'labAudModVo_span_nameVo': ['innerHTML__+Voz '],
    'audMod_label_labAutoPlay': [],
    'labAutoPlay_input_autoPlay': ['type__checkbox'],
    'labAutoPlay_span_nameAutoPlay': ['innerHTML__AutoPlay'],
    'secPlayer_p_pFindHymn': [],
    'pFindHymn_input_findHymn': ['type__text', 'placeholder__ Buscar Hino'],
    'pFindHymn_label_labFindMod': [],
    'labFindMod_input_findMod': ['type__checkbox'],
    'labFindMod_span_nameFindMod': ['innerHTML__Somente no título'],
    'root_section_secOut': [],
    'secOut_ul_listHymns': []
}